### ISSUE TITLE
Please add support for X

### ISSUE THREAD

**Issue by bLueriVerLHR** [NEUgenshiken/chatBot#5]
Like what quantum poetry did, if detecting a href to x [dot] com, take a snapshot or try to downloads the pictures.
Need more discussion.

**Comment by kahuuchino** [comment]
I think it isnt a useful feature.
First, a stable proxy environment is necessary to access X/twitter. It means bot need additional internet setting. Second, poetry will send pictures when he send a link of X, so a snapshot is redundancy.
In fact, I have tried to apply a twitter api 5 years ago, but they reject my application.
In my opinion, the post filled with word and discussion will not be easy to share like ngabbs ( or hard to open by link ), so the viewers need a snapshot . But X/twitter like weibo, will not have long discussion of article, will be easy to share by a screenshot or save to local device.

**Comment by bLueriVerLHR** [comment]
Thank you!
